spring:
  application:
    name: gpt-blog-backend
  profiles:
    include:
      - appKey
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    paswword:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create #?????? ??? ???? ??? ?? ??
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:db/data.sql


logging:
  level:
    com.study.boardExample: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace #?? ???? ???? ??